[2024-11-28T19:30:05.660+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T19:30:05.687+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_csv_files.read_csv_file manual__2024-11-28T19:30:04.271940+00:00 [queued]>
[2024-11-28T19:30:05.699+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_csv_files.read_csv_file manual__2024-11-28T19:30:04.271940+00:00 [queued]>
[2024-11-28T19:30:05.700+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-28T19:30:05.722+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): read_csv_file> on 2024-11-28 19:30:04.271940+00:00
[2024-11-28T19:30:05.733+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=303) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-28T19:30:05.735+0000] {standard_task_runner.py:72} INFO - Started process 305 to run task
[2024-11-28T19:30:05.733+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'process_csv_files', 'read_csv_file', 'manual__2024-11-28T19:30:04.271940+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmppbvnv6vv']
[2024-11-28T19:30:05.736+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask read_csv_file
[2024-11-28T19:30:05.804+0000] {task_command.py:467} INFO - Running <TaskInstance: process_csv_files.read_csv_file manual__2024-11-28T19:30:04.271940+00:00 [running]> on host 5a34bc2a3776
[2024-11-28T19:30:05.938+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_csv_files' AIRFLOW_CTX_TASK_ID='read_csv_file' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T19:30:04.271940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T19:30:04.271940+00:00'
[2024-11-28T19:30:05.940+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T19:30:21.408+0000] {logging_mixin.py:190} INFO -    order_id  user_id  ... order_hour_of_day  days_since_prior_order
0   2539329        1  ...                 8                     NaN
1   2398795        1  ...                 7                    15.0
2    473747        1  ...                12                    21.0
3   2254736        1  ...                 7                    29.0
4    431534        1  ...                15                    28.0

[5 rows x 7 columns]
[2024-11-28T19:30:21.435+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-28T19:30:21.448+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T19:30:21.449+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=process_csv_files, task_id=read_csv_file, run_id=manual__2024-11-28T19:30:04.271940+00:00, execution_date=20241128T193004, start_date=20241128T193005, end_date=20241128T193021
[2024-11-28T19:30:21.508+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-28T19:30:21.527+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T19:30:21.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
