[2024-12-28T20:43:43.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T20:43:43.595+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_fact_instacart manual__2024-12-26T15:23:11.859664+00:00 [queued]>
[2024-12-28T20:43:43.606+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_fact_instacart manual__2024-12-26T15:23:11.859664+00:00 [queued]>
[2024-12-28T20:43:43.607+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-28T20:43:43.622+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_fact_instacart> on 2024-12-26 15:23:11.859664+00:00
[2024-12-28T20:43:43.676+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2829) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-28T20:43:43.678+0000] {standard_task_runner.py:72} INFO - Started process 2831 to run task
[2024-12-28T20:43:43.676+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_fact_instacart', 'manual__2024-12-26T15:23:11.859664+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmp8bzkgwx5']
[2024-12-28T20:43:43.679+0000] {standard_task_runner.py:105} INFO - Job 296: Subtask etl_fact_instacart
[2024-12-28T20:43:43.902+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_fact_instacart manual__2024-12-26T15:23:11.859664+00:00 [running]> on host e3ff7ec590df
[2024-12-28T20:43:44.293+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_fact_instacart' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T15:23:11.859664+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T15:23:11.859664+00:00'
[2024-12-28T20:43:44.294+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T20:44:11.654+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-28T20:44:11.778+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T20:44:11.784+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instacart_etl, task_id=etl_fact_instacart, run_id=manual__2024-12-26T15:23:11.859664+00:00, execution_date=20241226T152311, start_date=20241228T204343, end_date=20241228T204411
[2024-12-28T20:44:11.936+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-28T20:44:12.004+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T20:44:12.008+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
