[2024-12-17T12:20:41.621+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T12:20:41.638+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_order_products manual__2024-12-17T11:52:07.046903+00:00 [queued]>
[2024-12-17T12:20:41.653+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instacart_etl.etl_dim_order_products manual__2024-12-17T11:52:07.046903+00:00 [queued]>
[2024-12-17T12:20:41.653+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2024-12-17T12:20:41.671+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_dim_order_products> on 2024-12-17 11:52:07.046903+00:00
[2024-12-17T12:20:41.684+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4955) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-17T12:20:41.683+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instacart_etl', 'etl_dim_order_products', 'manual__2024-12-17T11:52:07.046903+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/instacart_etl_dag.py', '--cfg-path', '/tmp/tmp41m3ngis']
[2024-12-17T12:20:41.686+0000] {standard_task_runner.py:72} INFO - Started process 4957 to run task
[2024-12-17T12:20:41.686+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask etl_dim_order_products
[2024-12-17T12:20:41.735+0000] {task_command.py:467} INFO - Running <TaskInstance: instacart_etl.etl_dim_order_products manual__2024-12-17T11:52:07.046903+00:00 [running]> on host ad3472fa3861
[2024-12-17T12:20:41.820+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instacart_etl' AIRFLOW_CTX_TASK_ID='etl_dim_order_products' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T11:52:07.046903+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T11:52:07.046903+00:00'
[2024-12-17T12:20:41.822+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T12:21:13.775+0000] {job.py:229} INFO - Heartbeat recovered after 16.56 seconds
[2024-12-17T12:21:13.793+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2024-12-17T12:21:13.825+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-17T12:21:13.830+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
