[2024-12-11T09:12:16.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-11T09:12:16.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_sql_server_connection.test_connection manual__2024-12-11T09:12:14.531580+00:00 [queued]>
[2024-12-11T09:12:16.442+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_sql_server_connection.test_connection manual__2024-12-11T09:12:14.531580+00:00 [queued]>
[2024-12-11T09:12:16.443+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-11T09:12:16.464+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_connection> on 2024-12-11 09:12:14.531580+00:00
[2024-12-11T09:12:16.479+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=866) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-11T09:12:16.478+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_sql_server_connection', 'test_connection', 'manual__2024-12-11T09:12:14.531580+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/test_etl_dag.py', '--cfg-path', '/tmp/tmp_basfbff']
[2024-12-11T09:12:16.480+0000] {standard_task_runner.py:72} INFO - Started process 867 to run task
[2024-12-11T09:12:16.481+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask test_connection
[2024-12-11T09:12:16.548+0000] {task_command.py:467} INFO - Running <TaskInstance: test_sql_server_connection.test_connection manual__2024-12-11T09:12:14.531580+00:00 [running]> on host 072f034d0d3f
[2024-12-11T09:12:16.698+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_sql_server_connection' AIRFLOW_CTX_TASK_ID='test_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T09:12:14.531580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T09:12:14.531580+00:00'
[2024-12-11T09:12:16.700+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-11T09:12:16.741+0000] {base.py:84} INFO - Retrieving connection 'mssql_default'
[2024-12-11T09:12:16.838+0000] {logging_mixin.py:190} INFO - SQL Server Connection Test Successful: (datetime.datetime(2024, 12, 11, 9, 12, 16, 833000),)
[2024-12-11T09:12:16.840+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-11T09:12:16.860+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-11T09:12:16.862+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_sql_server_connection, task_id=test_connection, run_id=manual__2024-12-11T09:12:14.531580+00:00, execution_date=20241211T091214, start_date=20241211T091216, end_date=20241211T091216
[2024-12-11T09:12:16.901+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-11T09:12:16.926+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T09:12:16.931+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
